# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fialexan <fialexan@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/03 16:13:48 by fialexan          #+#    #+#              #
#    Updated: 2022/03/03 16:23:10 by fialexan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SCRS = 

OBJS = $(SCRS:.c=.o)

BONUS = 

BONUS_OBJS = $(BONUS:.c=.o)

NAME = 

CFLAGS = -Wall -Werror -Wextra -g -c -D BUFFER_SIZE=10